apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.productService.replicas }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: {{ .Values.productService.image }}
          ports:
            - containerPort: {{ .Values.productService.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.productService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: {{ .Values.productService.service.type }}
  selector:
    app: product-service
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: {{ .Values.productService.port }}
