trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/**

pool:
  vmImage: ubuntu-latest

variables:
  acrLoginServer: ecommerceacr.azurecr.io
  imageTag: $(Build.BuildId)

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: Build & Push frontend
            inputs:
              containerRegistry: acr-service-connection
              repository: frontend
              command: buildAndPush
              dockerfile: services/frontend/Dockerfile
              buildContext: services/frontend
              tags: |
                $(imageTag)
                latest

          - task: DotNetCoreCLI@2
            displayName: Build product-service
            inputs:
              command: publish
              publishWebProjects: false
              projects: services/product-service/product-service.csproj
              arguments: -c Release -o $(Build.ArtifactStagingDirectory)/product-service

          - task: Docker@2
            displayName: Build & Push product-service
            inputs:
              containerRegistry: acr-service-connection
              repository: product-service
              command: buildAndPush
              dockerfile: services/product-service/Dockerfile
              buildContext: services/product-service
              tags: |
                $(imageTag)
                latest

          - task: DotNetCoreCLI@2
            displayName: Build order-service
            inputs:
              command: publish
              publishWebProjects: false
              projects: services/order-service/order-service.csproj
              arguments: -c Release -o $(Build.ArtifactStagingDirectory)/order-service

          - task: Docker@2
            displayName: Build & Push order-service
            inputs:
              containerRegistry: acr-service-connection
              repository: order-service
              command: buildAndPush
              dockerfile: services/order-service/Dockerfile
              buildContext: services/order-service
              tags: |
                $(imageTag)
                latest
